#!/usr/bin/env python3
"""
Axeng CLI - Interactive configuration and chat interface
Similar to OpenCode's experience
"""
import os
import sys
import json
import subprocess
from pathlib import Path
from typing import Optional

try:
    import typer
    from rich.console import Console
    from rich.prompt import Prompt, Confirm
    from rich.panel import Panel
    from rich.markdown import Markdown
    from rich.progress import Progress, SpinnerColumn, TextColumn
except ImportError:
    print("Installing required dependencies...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "typer", "rich", "--quiet"])
    import typer
    from rich.console import Console
    from rich.prompt import Prompt, Confirm
    from rich.panel import Panel
    from rich.markdown import Markdown
    from rich.progress import Progress, SpinnerColumn, TextColumn

app = typer.Typer(
    name="axeng",
    help="Engineering Manager Accelerator - AI chief of staff for dev teams",
    add_completion=False
)
console = Console()

# Config paths
AXENG_HOME = Path(os.getenv("AXENG_HOME", Path.home() / ".axeng"))
CONFIG_FILE = AXENG_HOME / "config.json"
ENV_FILE = AXENG_HOME / ".env"

def load_config() -> dict:
    """Load existing configuration"""
    if CONFIG_FILE.exists():
        return json.loads(CONFIG_FILE.read_text())
    return {}

def save_config(config: dict):
    """Save configuration"""
    AXENG_HOME.mkdir(parents=True, exist_ok=True)
    CONFIG_FILE.write_text(json.dumps(config, indent=2))

def update_env_file(config: dict):
    """Update .env file from config"""
    env_lines = []

    # Header
    env_lines.append("# Axeng Configuration")
    env_lines.append("# Generated by: axeng configure")
    env_lines.append("")

    # LLM Provider
    if config.get("llm_provider"):
        provider = config["llm_provider"]
        env_lines.append("# LLM Provider")
        env_lines.append(f"LLM_PROVIDER_ORDER={provider}")

        if provider == "opencode":
            env_lines.append(f"OPENCODE_API_KEY={config.get('opencode_api_key', '')}")
            env_lines.append(f"OPENCODE_MODEL={config.get('opencode_model', 'minimax-m2.5-free')}")
        elif provider == "anthropic":
            env_lines.append(f"ANTHROPIC_API_KEY={config.get('anthropic_api_key', '')}")
        elif provider == "openai":
            env_lines.append(f"OPENAI_API_KEY={config.get('openai_api_key', '')}")
        env_lines.append("")

    # GitHub
    if config.get("github_token"):
        env_lines.append("# GitHub")
        env_lines.append(f"GITHUB_TOKEN={config['github_token']}")
        env_lines.append("")

    # Linear
    if config.get("linear_api_key"):
        env_lines.append("# Linear")
        env_lines.append(f"LINEAR_API_KEY={config['linear_api_key']}")
        env_lines.append("")

    # Telegram (optional)
    if config.get("telegram_bot_token"):
        env_lines.append("# Telegram")
        env_lines.append(f"TELEGRAM_BOT_TOKEN={config['telegram_bot_token']}")
        env_lines.append(f"TELEGRAM_CHAT_ID={config.get('telegram_chat_id', '')}")
        env_lines.append("")

    # Google (optional)
    if config.get("google_enabled"):
        env_lines.append("# Google Workspace")
        env_lines.append("GOOGLE_CLIENT_SECRET=~/.hermes/secrets/google_client_secret.json")
        env_lines.append("GOOGLE_TOKEN_PATH=~/.hermes/secrets/google_token.json")
        env_lines.append("")

    ENV_FILE.write_text("\n".join(env_lines))

@app.command()
def configure():
    """
    Interactive configuration wizard for Axeng
    """
    console.print(Panel.fit(
        "[bold cyan]Axeng Configuration Wizard[/bold cyan]\n"
        "Let's set up your AI chief of staff",
        border_style="cyan"
    ))
    console.print()

    config = load_config()

    # Step 1: LLM Provider
    console.print("[bold]Step 1: Choose your LLM provider[/bold]")
    console.print("Axeng needs an AI model to generate reports and insights.\n")

    llm_choice = Prompt.ask(
        "Which provider would you like to use?",
        choices=["opencode", "anthropic", "openai", "groq"],
        default=config.get("llm_provider", "opencode")
    )
    config["llm_provider"] = llm_choice

    # Get API key for chosen provider
    if llm_choice == "opencode":
        console.print("\n[cyan]OpenCode Zen[/cyan] - Free models available!")
        console.print("Get your API key at: https://opencode.ai/")
        api_key = Prompt.ask(
            "OpenCode API key",
            default=config.get("opencode_api_key", ""),
            password=True
        )
        config["opencode_api_key"] = api_key

        model = Prompt.ask(
            "Model",
            default=config.get("opencode_model", "minimax-m2.5-free"),
            choices=["minimax-m2.5-free", "deepseek-v4-flash-free", "big-pickle"]
        )
        config["opencode_model"] = model

    elif llm_choice == "anthropic":
        console.print("\n[cyan]Anthropic Claude[/cyan] - Best quality")
        console.print("Get your API key at: https://console.anthropic.com/")
        api_key = Prompt.ask(
            "Anthropic API key",
            default=config.get("anthropic_api_key", ""),
            password=True
        )
        config["anthropic_api_key"] = api_key

    elif llm_choice == "openai":
        console.print("\n[cyan]OpenAI[/cyan] - Most compatible")
        console.print("Get your API key at: https://platform.openai.com/")
        api_key = Prompt.ask(
            "OpenAI API key",
            default=config.get("openai_api_key", ""),
            password=True
        )
        config["openai_api_key"] = api_key

    console.print("\n[green]✓[/green] LLM provider configured\n")

    # Step 2: GitHub
    console.print("[bold]Step 2: GitHub integration[/bold]")
    console.print("Connect to GitHub to track repos, PRs, and issues.\n")

    github_token = Prompt.ask(
        "GitHub token (or press Enter to use 'gh' CLI)",
        default=config.get("github_token", ""),
        password=True
    )
    if github_token:
        config["github_token"] = github_token
    else:
        console.print("[dim]Will use GitHub CLI (gh auth login)[/dim]")

    console.print("[green]✓[/green] GitHub configured\n")

    # Step 3: Linear
    console.print("[bold]Step 3: Linear integration[/bold]")
    console.print("Connect to Linear to manage issues and projects.\n")
    console.print("Get your API key at: https://linear.app/settings/api\n")

    linear_key = Prompt.ask(
        "Linear API key",
        default=config.get("linear_api_key", ""),
        password=True
    )
    config["linear_api_key"] = linear_key

    console.print("[green]✓[/green] Linear configured\n")

    # Step 4: Optional services
    console.print("[bold]Step 4: Optional services[/bold]\n")

    # Telegram
    if Confirm.ask("Set up Telegram notifications?", default=config.get("telegram_bot_token") is not None):
        console.print("\nTalk to @BotFather on Telegram to create a bot\n")
        bot_token = Prompt.ask(
            "Telegram bot token",
            default=config.get("telegram_bot_token", ""),
            password=True
        )
        chat_id = Prompt.ask(
            "Telegram chat ID",
            default=config.get("telegram_chat_id", "")
        )
        config["telegram_bot_token"] = bot_token
        config["telegram_chat_id"] = chat_id
        console.print("[green]✓[/green] Telegram configured")

    # Google
    if Confirm.ask("\nSet up Google Calendar integration?", default=config.get("google_enabled", False)):
        console.print("\n[cyan]Google Workspace Setup:[/cyan]")
        console.print("1. Go to https://console.cloud.google.com/")
        console.print("2. Enable Calendar API + Gmail API")
        console.print("3. Create OAuth credentials")
        console.print("4. Download and save to ~/.hermes/secrets/google_client_secret.json")
        console.print("")

        if Confirm.ask("Have you saved the client secret?"):
            config["google_enabled"] = True
            console.print("[green]✓[/green] Google workspace enabled")
            console.print("[dim]Run 'axeng google auth' to complete setup[/dim]")

    console.print()

    # Save configuration
    save_config(config)
    update_env_file(config)

    console.print(Panel.fit(
        "[bold green]✓ Configuration complete![/bold green]\n\n"
        f"Config saved to: {CONFIG_FILE}\n"
        f"Environment: {ENV_FILE}\n\n"
        "[cyan]Next steps:[/cyan]\n"
        "  axeng start    - Start the service\n"
        "  axeng chat     - Chat with Axeng\n"
        "  axeng status   - Check service status",
        border_style="green"
    ))

@app.command()
def chat(history: bool = typer.Option(False, "--history", help="Show chat history")):
    """
    Interactive chat with Axeng
    """
    axeng_home = Path(os.getenv("AXENG_HOME", str(Path.home() / ".axeng")))
    history_file = axeng_home / "chat_history.json"

    # Show history if requested
    if history:
        if not history_file.exists():
            console.print("[yellow]No chat history found[/yellow]")
            return

        import json
        with open(history_file) as f:
            history_data = json.load(f)

        console.print("[bold]Chat History[/bold] (last 10 conversations)\n")
        for entry in history_data[-10:]:
            timestamp = entry.get("timestamp", "")
            user_q = entry.get("user", "")[:60]
            console.print(f"[dim]{timestamp}[/dim]")
            console.print(f"  You: {user_q}")
            console.print()
        return

    console.print(Panel.fit(
        "[bold cyan]Axeng Chat[/bold cyan]\n"
        "Ask me about your team, projects, or engineering metrics",
        border_style="cyan"
    ))
    console.print()

    # Show smart suggestions
    try:
        sys.path.insert(0, str(Path(__file__).parent))
        from smart_suggestions import get_smart_suggestions, format_suggestions_for_display

        suggestions = get_smart_suggestions(limit=3)
        if suggestions:
            console.print(format_suggestions_for_display(suggestions))
            console.print()
    except Exception:
        # Silently skip if suggestions fail
        pass

    # Check if configured
    config = load_config()
    if not config.get("llm_provider"):
        console.print("[red]Error:[/red] Axeng not configured")
        console.print("Run: [cyan]axeng configure[/cyan]\n")
        raise typer.Exit(1)

    # Load history
    chat_history = []
    if history_file.exists():
        try:
            with open(history_file) as f:
                chat_history = json.load(f)
        except:
            chat_history = []

    # Load environment and orchestrator
    try:
        # Load environment variables from AXENG_HOME
        axeng_home = Path(os.getenv("AXENG_HOME", Path.home() / ".axeng"))
        env_file = axeng_home / ".env"

        if env_file.exists():
            # Load .env file
            for line in env_file.read_text().splitlines():
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    os.environ[key.strip()] = value.strip()

        sys.path.insert(0, str(Path(__file__).parent))
        import orchestrator
        import logging

        # Suppress noisy logging
        logging.getLogger("llm_gateway").setLevel(logging.ERROR)
        logging.getLogger("orchestrator").setLevel(logging.ERROR)

        console.print("[green]✓[/green] Ready\n")

    except Exception as e:
        console.print(f"[red]Error loading Axeng:[/red] {e}")
        console.print("Run: [cyan]axeng configure[/cyan] to set up your provider\n")
        raise typer.Exit(1)

    console.print("[dim]Type 'exit' or 'quit' to end the chat[/dim]")
    console.print("[dim]Enter a number (1-3) to use a suggested query, or 'suggestions' to refresh[/dim]\n")

    # Store suggestions for selection
    current_suggestions = []
    try:
        from smart_suggestions import get_smart_suggestions
        current_suggestions = get_smart_suggestions(limit=3)
    except:
        pass

    # Chat loop with orchestrator
    while True:
        try:
            user_input = Prompt.ask("[bold cyan]You[/bold cyan]")

            if user_input.lower() in ["exit", "quit", "bye"]:
                console.print("\n[cyan]Goodbye! 👋[/cyan]\n")
                break

            # Refresh suggestions
            if user_input.lower() in ["suggestions", "suggest", "help"]:
                try:
                    from smart_suggestions import get_smart_suggestions, format_suggestions_for_display
                    current_suggestions = get_smart_suggestions(limit=3)
                    console.print("\n" + format_suggestions_for_display(current_suggestions) + "\n")
                except Exception as e:
                    console.print(f"[red]Error loading suggestions:[/red] {e}\n")
                continue

            # Check if user selected a suggestion by number
            if user_input.strip() in ["1", "2", "3"] and current_suggestions:
                idx = int(user_input.strip()) - 1
                if 0 <= idx < len(current_suggestions):
                    user_input = current_suggestions[idx]["query"]
                    console.print(f"[dim]Using: {user_input}[/dim]\n")

            # Call orchestrator (it handles tool routing + LLM synthesis)
            console.print(f"\n[bold green]Axeng[/bold green]: ", end="")

            with console.status("[dim]...[/dim]"):
                try:
                    # Use orchestrator to route query to tools and synthesize response
                    result = orchestrator.orchestrate(
                        goal=user_input,
                        auto_sync=False,  # Don't auto-sync on every query
                        use_llm=True,
                        provider=config.get("llm_provider", "opencode"),
                        quiet=True  # Suppress debug output
                    )

                    # orchestrate returns the synthesized text response
                    console.print(result + "\n")

                    # Save to history
                    from datetime import datetime
                    chat_history.append({
                        "timestamp": datetime.now().isoformat(),
                        "user": user_input,
                        "response": result[:200]  # Save first 200 chars
                    })

                    # Keep only last 50 conversations
                    chat_history = chat_history[-50:]

                    # Save to file
                    history_file.parent.mkdir(parents=True, exist_ok=True)
                    with open(history_file, 'w') as f:
                        json.dump(chat_history, f, indent=2)

                except Exception as e:
                    console.print(f"[red]Error: {e}[/red]\n")

        except KeyboardInterrupt:
            console.print("\n\n[cyan]Goodbye! 👋[/cyan]\n")
            break
        except Exception as e:
            console.print(f"\n[red]Error:[/red] {e}\n")
            continue

@app.command()
def start():
    """Start Axeng service"""
    console.print("[cyan]Starting Axeng...[/cyan]")

    # Check if already running
    import socket
    def is_port_in_use(port):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            return s.connect_ex(('localhost', port)) == 0

    if is_port_in_use(3000) and is_port_in_use(3457):
        console.print("[yellow]⚠[/yellow] Axeng appears to be already running")
        console.print("[bold]Next.js UI:[/bold] [link]http://localhost:3000[/link]")
        console.print("[bold]API:[/bold] [link]http://localhost:3457[/link]")
        console.print("\n[dim]Run 'axeng status' to check or 'axeng stop' to stop it[/dim]")
        return

    # Check configuration
    if not CONFIG_FILE.exists():
        console.print("[yellow]Warning:[/yellow] Not configured via CLI")
        console.print("You can run: [cyan]axeng configure[/cyan]")
        console.print("Or edit: [cyan]~/.hermes/.env[/cyan] and [cyan]config/config.yaml[/cyan]\n")

    # Find axeng directory
    axeng_dir = Path(__file__).parent.parent

    # Check if Next.js dependencies are installed
    ui_dir = axeng_dir / "ui" / "nextjs"
    if not (ui_dir / "node_modules").exists():
        console.print("[yellow]Installing dependencies...[/yellow]")
        result = subprocess.run(
            ["npm", "install"],
            cwd=ui_dir,
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            console.print("[red]Error installing dependencies[/red]")
            console.print(result.stderr)
            raise typer.Exit(1)

    # Start using make (don't capture output, let it run in background)
    console.print("[cyan]Starting Axeng Next.js UI...[/cyan]")
    subprocess.Popen(
        ["make", "start"],
        cwd=axeng_dir,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )

    # Wait a moment for services to start
    import time
    time.sleep(3)

    # Check if services started
    if is_port_in_use(3000) or is_port_in_use(3457):
        console.print("[green]✓[/green] Axeng started")
        console.print("\n[bold]Next.js UI:[/bold] [link]http://localhost:3000[/link]")
        console.print("[bold]API:[/bold] [link]http://localhost:3457[/link]")
        console.print("\n[dim]Logs: tail -f /tmp/axeng-*.log[/dim]")
    else:
        console.print("[yellow]⚠[/yellow] Services may take a moment to start")
        console.print("[dim]Check status: axeng status[/dim]")
        console.print("[dim]View logs: axeng logs[/dim]")

@app.command()
def stop():
    """Stop Axeng service"""
    console.print("[cyan]Stopping Axeng...[/cyan]")

    axeng_dir = Path(__file__).parent.parent
    result = subprocess.run(
        ["make", "stop"],
        cwd=axeng_dir,
        capture_output=True,
        text=True
    )

    if result.returncode == 0:
        console.print("[green]✓[/green] Axeng stopped")
    else:
        console.print("[red]Error stopping Axeng[/red]")
        console.print(result.stderr)

@app.command()
def status():
    """Check Axeng service and integrations status"""
    import socket
    import json

    def is_port_in_use(port):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            return s.connect_ex(('localhost', port)) == 0

    console.print("[bold]Axeng Status[/bold]\n")

    # Service status
    ui_running = is_port_in_use(3000)
    api_running = is_port_in_use(3457)

    console.print("[bold cyan]Services:[/bold cyan]")
    if ui_running and api_running:
        console.print("  [green]✓[/green] Running - [link]http://localhost:3000[/link]")
    elif ui_running or api_running:
        console.print("  [yellow]⚠[/yellow] Partially running")
    else:
        console.print("  [yellow]○[/yellow] Stopped - run [cyan]axeng start[/cyan]")

    # Integration status
    console.print("\n[bold cyan]Integrations:[/bold cyan]")

    # Check Linear
    axeng_home = os.getenv("AXENG_HOME", str(Path.home() / ".axeng"))
    env = {**os.environ, "AXENG_HOME": axeng_home}

    try:
        result = subprocess.run(
            ["python3", str(Path(__file__).parent / "tools" / "linear_tool.py"), "mine"],
            capture_output=True, text=True, timeout=5, env=env
        )
        data = json.loads(result.stdout)
        if "error" not in data:
            console.print(f"  [green]✓[/green] Linear - {data.get('total', 0)} issues assigned to you")
        else:
            console.print(f"  [red]✗[/red] Linear - {data['error']}")
    except:
        console.print("  [yellow]⚠[/yellow] Linear - Not configured")

    # Check GitHub (quick test)
    if os.getenv("GITHUB_TOKEN") or "GITHUB_TOKEN" in open(Path(axeng_home) / ".env").read() if (Path(axeng_home) / ".env").exists() else "":
        console.print("  [green]✓[/green] GitHub - Connected")
    else:
        console.print("  [yellow]⚠[/yellow] GitHub - Token not configured")

    # Check LLM
    llm_provider = None
    config_file = Path(axeng_home) / "config.json"
    if config_file.exists():
        with open(config_file) as f:
            config = json.load(f)
            llm_provider = config.get("llm_provider")
            llm_model = config.get(f"{llm_provider}_model")
            if llm_provider:
                console.print(f"  [green]✓[/green] LLM - {llm_provider}" + (f"/{llm_model}" if llm_model else ""))
            else:
                console.print("  [yellow]⚠[/yellow] LLM - Not configured")
    else:
        console.print("  [yellow]⚠[/yellow] LLM - Run [cyan]axeng configure[/cyan]")

    # Check optional services
    console.print("\n[bold cyan]Optional:[/bold cyan]")
    console.print("  [dim]Calendar[/dim] - Run [cyan]axeng configure[/cyan] to set up")
    console.print("  [dim]Obsidian[/dim] - Configure vault path in config")

    console.print()

@app.command()
def logs():
    """View Axeng logs"""
    axeng_dir = Path(__file__).parent.parent
    subprocess.run(["make", "logs"], cwd=axeng_dir)

@app.command()
def update():
    """Update Axeng to latest version"""
    console.print("[cyan]Updating Axeng...[/cyan]")

    axeng_dir = Path(__file__).parent.parent
    result = subprocess.run(
        ["make", "update"],
        cwd=axeng_dir,
        capture_output=True,
        text=True
    )

    if result.returncode == 0:
        console.print("[green]✓[/green] Updated successfully")
    else:
        console.print("[red]Error updating[/red]")
        console.print(result.stderr)

@app.command()
def ooo():
    """Show who is out of office today"""
    console.print("[cyan]Checking vacations...[/cyan]\n")

    try:
        result = subprocess.run(
            ["python3", str(Path(__file__).parent / "tools" / "vacations.py"), "today"],
            capture_output=True,
            text=True,
            env={**os.environ, "AXENG_HOME": os.getenv("AXENG_HOME", str(Path.home() / ".axeng"))}
        )

        import json
        data = json.loads(result.stdout)

        if data["total"] == 0:
            console.print("[green]✓[/green] No one is OOO today")
        else:
            console.print(f"[yellow]{data['total']}[/yellow] person(s) OOO today:\n")
            for v in data["vacations"]:
                date_range = f"{v['start']} to {v['end']}"
                console.print(f"  • [bold]{v['name']}[/bold]: {date_range}")
                console.print(f"    {v['url']}\n")

    except Exception as e:
        console.print(f"[red]Error:[/red] {e}")


@app.command()
def issues():
    """Show my Linear issues"""
    console.print("[cyan]Fetching your Linear issues...[/cyan]\n")

    try:
        axeng_home = os.getenv("AXENG_HOME", str(Path.home() / ".axeng"))
        result = subprocess.run(
            ["python3", str(Path(__file__).parent / "tools" / "linear_tool.py"), "mine"],
            capture_output=True,
            text=True,
            env={**os.environ, "AXENG_HOME": axeng_home}
        )

        import json
        data = json.loads(result.stdout)

        if "error" in data:
            console.print(f"[red]Error:[/red] {data['error']}")
            console.print("Run: [cyan]axeng configure[/cyan]")
            return

        if data["total"] == 0:
            console.print("[green]✓[/green] No issues assigned to you")
        else:
            console.print(f"[bold]{data['total']}[/bold] issue(s) assigned to you:\n")

            # Group by state
            for state, issues in data["by_state"].items():
                if issues:
                    console.print(f"[bold cyan]{state}:[/bold cyan]")
                    for issue in issues:
                        console.print(f"  • {issue}")
                    console.print()

    except Exception as e:
        console.print(f"[red]Error:[/red] {e}")


@app.command()
def prs():
    """Show my GitHub pull requests"""
    console.print("[cyan]Fetching your GitHub PRs...[/cyan]\n")

    try:
        axeng_home = os.getenv("AXENG_HOME", str(Path.home() / ".axeng"))
        result = subprocess.run(
            ["python3", str(Path(__file__).parent / "tools" / "github_activity.py")],
            capture_output=True,
            text=True,
            timeout=30,  # Increased from 10s for GitHub API
            env={**os.environ, "AXENG_HOME": axeng_home}
        )

        import json
        data = json.loads(result.stdout) if result.stdout.strip() else {}

        if "error" in data:
            console.print(f"[red]Error:[/red] {data['error']}")
            console.print("Run: [cyan]axeng configure[/cyan]")
            return

        # Parse PR data from github_activity output
        prs = data.get("prs", []) if isinstance(data, dict) else []

        if not prs:
            console.print("[green]✓[/green] No open PRs")
        else:
            console.print(f"[bold]{len(prs)}[/bold] open PR(s):\n")
            for pr in prs[:10]:  # Show first 10
                console.print(f"  • [bold]{pr.get('title', 'Untitled')}[/bold]")
                if pr.get('url'):
                    console.print(f"    {pr['url']}")
                console.print()

    except Exception as e:
        console.print(f"[red]Error:[/red] {e}")
        console.print("\n[dim]Tip: Use 'axeng chat' and ask 'show my PRs'[/dim]")


@app.command(name="pr-health")
def pr_health(days: int = typer.Option(14, "--days", "-d", help="Days to analyze")):
    """Analyze PR health: stale PRs, review bottlenecks, velocity"""
    console.print(f"[cyan]Analyzing PR health (last {days} days)...[/cyan]\n")

    try:
        axeng_home = os.getenv("AXENG_HOME", str(Path.home() / ".axeng"))
        result = subprocess.run(
            ["python3", str(Path(__file__).parent / "tools" / "github_activity.py"), "pr-health", "", str(days)],
            capture_output=True,
            text=True,
            timeout=30,
            env={**os.environ, "AXENG_HOME": axeng_home}
        )

        import json
        data = json.loads(result.stdout) if result.stdout.strip() else {}

        if "error" in data:
            console.print(f"[red]Error:[/red] {data['error']}")
            if "hint" in data:
                console.print(f"[yellow]Hint:[/yellow] {data['hint']}")
            return

        metrics = data.get("metrics", {})
        insights = data.get("insights", [])
        stale_prs = data.get("stale_prs", [])
        needs_review = data.get("needs_review", [])

        # Show metrics
        console.print(Panel.fit(
            f"[bold]Total Open:[/bold] {metrics.get('total_open', 0)}\n"
            f"[bold]Stale (>3d):[/bold] {metrics.get('stale_count', 0)}\n"
            f"[bold]Needs Review:[/bold] {metrics.get('needs_review', 0)}\n"
            f"[bold]Approved:[/bold] {metrics.get('approved', 0)}\n"
            f"[bold]Changes Requested:[/bold] {metrics.get('changes_requested', 0)}\n"
            f"[bold]Avg Age:[/bold] {metrics.get('avg_age_days', 0)} days\n"
            f"[bold]Review Velocity:[/bold] {metrics.get('review_velocity_per_day', 0)} PRs/day",
            title="📊 PR Health Metrics",
            border_style="cyan"
        ))

        # Show insights
        if insights:
            console.print("\n[bold]💡 Insights:[/bold]\n")
            for insight in insights:
                level = insight.get("level", "info")
                emoji = {
                    "critical": "🔴",
                    "warning": "🟡",
                    "info": "🔵",
                    "success": "✅"
                }.get(level, "ℹ️")

                console.print(f"{emoji} [bold]{insight.get('message')}[/bold]")
                console.print(f"   → {insight.get('action')}\n")

        # Show stale PRs
        if stale_prs:
            console.print("\n[bold]🕐 Stale PRs (>3 days):[/bold]\n")
            for pr in stale_prs[:5]:
                age = pr.get("age_days", 0)
                console.print(f"  • [bold]{pr.get('title')}[/bold] ({age}d old)")
                console.print(f"    {pr.get('repo')} #{pr.get('number')} - {pr.get('review_status')}")
                if pr.get("url"):
                    console.print(f"    [link]{pr['url']}[/link]")
                console.print()

        # Show PRs needing review
        if needs_review and len(needs_review) > 0:
            console.print("\n[bold]👀 PRs Needing First Review:[/bold]\n")
            for pr in needs_review[:5]:
                console.print(f"  • [bold]{pr.get('title')}[/bold]")
                console.print(f"    {pr.get('repo')} #{pr.get('number')} by @{pr.get('author')}")
                if pr.get("url"):
                    console.print(f"    [link]{pr['url']}[/link]")
                console.print()

    except subprocess.TimeoutExpired:
        console.print("[red]Timeout:[/red] GitHub API is slow. Try again later.")
    except Exception as e:
        console.print(f"[red]Error:[/red] {e}")
        console.print("\n[dim]Tip: Check your GitHub token with 'axeng status'[/dim]")


@app.command()
def standup(send: bool = typer.Option(False, "--send", help="Send to Telegram/Slack")):
    """Generate daily standup brief for team"""
    console.print("[cyan]Generating standup brief...[/cyan]\n")

    try:
        # Use orchestrator to generate standup
        axeng_home = os.getenv("AXENG_HOME", str(Path.home() / ".axeng"))

        # Load environment
        env_file = Path(axeng_home) / ".env"
        if env_file.exists():
            for line in env_file.read_text().splitlines():
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    os.environ[key.strip()] = value.strip()

        sys.path.insert(0, str(Path(__file__).parent))
        import orchestrator

        query = "Generate a standup brief: what shipped yesterday, who's blocked, PRs waiting for review, who's OOO today"
        result = orchestrator.orchestrate(
            goal=query,
            auto_sync=False,
            use_llm=True,
            quiet=True
        )

        console.print(result)

        if send:
            console.print("\n[dim]Sending to Telegram...[/dim]")
            # TODO: Implement Telegram send
            console.print("[yellow]⚠[/yellow] Telegram send not yet implemented")

    except Exception as e:
        console.print(f"[red]Error:[/red] {e}")


@app.command()
def prep(name: str = typer.Argument(None, help="Person's name or GitHub username")):
    """Prepare for 1:1 meeting with team member"""
    if not name:
        console.print("[yellow]Usage:[/yellow] axeng prep [name]")
        console.print("\nExample: axeng prep \"John Doe\"")
        return

    console.print(f"[cyan]Preparing 1:1 with {name}...[/cyan]\n")

    try:
        axeng_home = os.getenv("AXENG_HOME", str(Path.home() / ".axeng"))

        # Load environment
        env_file = Path(axeng_home) / ".env"
        if env_file.exists():
            for line in env_file.read_text().splitlines():
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    os.environ[key.strip()] = value.strip()

        sys.path.insert(0, str(Path(__file__).parent))
        import orchestrator

        query = f"Prepare a 1:1 meeting brief for {name}: their open issues, recent commits, pending PRs, last discussion notes, and suggested topics"
        result = orchestrator.orchestrate(
            goal=query,
            auto_sync=False,
            use_llm=True,
            quiet=True
        )

        console.print(result)

    except Exception as e:
        console.print(f"[red]Error:[/red] {e}")


@app.command()
def offboard(
    github_login: str = typer.Argument(..., help="GitHub username to offboard"),
    dry_run: bool = typer.Option(True, "--dry-run/--execute", help="Preview changes (default) or execute")
):
    """Offboard a team member from GitHub and Linear"""
    console.print(f"[cyan]Offboarding {github_login}...[/cyan]\n")

    if dry_run:
        console.print("[yellow]DRY RUN MODE[/yellow] - showing what would be removed\n")

    try:
        axeng_home = os.getenv("AXENG_HOME", str(Path.home() / ".axeng"))

        args = [
            "python3",
            str(Path(__file__).parent / "tools" / "offboarding.py"),
            github_login
        ]
        if dry_run:
            args.append("--dry-run")

        result = subprocess.run(
            args,
            capture_output=True,
            text=True,
            env={**os.environ, "AXENG_HOME": axeng_home}
        )

        console.print(result.stdout)

        if result.returncode != 0:
            console.print(f"\n[red]Error:[/red] {result.stderr}")
        elif dry_run:
            console.print("\n[dim]Run with[/dim] [cyan]--execute[/cyan] [dim]to perform offboarding[/dim]")

    except Exception as e:
        console.print(f"[red]Error:[/red] {e}")


@app.command()
def team(name: str = typer.Argument(None, help="Team name to show details")):
    """List teams or show team details"""
    import yaml

    axeng_home = os.getenv("AXENG_HOME", str(Path.home() / ".axeng"))
    config_file = Path(axeng_home) / "config" / "config.yaml"

    if not config_file.exists():
        console.print("[red]Error:[/red] config.yaml not found")
        console.print(f"Expected at: {config_file}")
        return

    try:
        with open(config_file) as f:
            config = yaml.safe_load(f)

        teams = config.get("linear", {}).get("projects", {})

        if not name:
            # List all teams
            console.print("[bold]Teams:[/bold]\n")
            for team_name, team_info in teams.items():
                console.print(f"  • [cyan]{team_name}[/cyan]")
                if team_info.get("owner"):
                    console.print(f"    Owner: {team_info['owner']}")
                if team_info.get("repos"):
                    console.print(f"    Repos: {', '.join(team_info['repos'][:3])}")
                console.print()
        else:
            # Show specific team
            team_info = teams.get(name)
            if not team_info:
                console.print(f"[red]Error:[/red] Team '{name}' not found")
                console.print(f"\nAvailable teams: {', '.join(teams.keys())}")
                return

            console.print(f"[bold cyan]{name}[/bold cyan]\n")
            console.print(f"Owner: {team_info.get('owner', 'Not set')}")
            console.print(f"Repos: {', '.join(team_info.get('repos', []))}")

    except Exception as e:
        console.print(f"[red]Error:[/red] {e}")


def main():
    """Main CLI entry point"""
    app()

if __name__ == "__main__":
    main()
