#!/usr/bin/env python3
"""
Axeng CLI - Interactive configuration and chat interface
Similar to OpenCode's experience
"""
import os
import sys
import json
import subprocess
from pathlib import Path
from typing import Optional

try:
    import typer
    from rich.console import Console
    from rich.prompt import Prompt, Confirm
    from rich.panel import Panel
    from rich.markdown import Markdown
    from rich.progress import Progress, SpinnerColumn, TextColumn
except ImportError:
    print("Installing required dependencies...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "typer", "rich", "--quiet"])
    import typer
    from rich.console import Console
    from rich.prompt import Prompt, Confirm
    from rich.panel import Panel
    from rich.markdown import Markdown
    from rich.progress import Progress, SpinnerColumn, TextColumn

app = typer.Typer(
    name="axeng",
    help="Engineering Manager Accelerator - AI chief of staff for dev teams",
    add_completion=False
)
console = Console()

# Config paths
AXENG_HOME = Path(os.getenv("AXENG_HOME", Path.home() / ".axeng"))
CONFIG_FILE = AXENG_HOME / "config.json"
ENV_FILE = AXENG_HOME / ".env"

def load_config() -> dict:
    """Load existing configuration"""
    if CONFIG_FILE.exists():
        return json.loads(CONFIG_FILE.read_text())
    return {}

def save_config(config: dict):
    """Save configuration"""
    AXENG_HOME.mkdir(parents=True, exist_ok=True)
    CONFIG_FILE.write_text(json.dumps(config, indent=2))

def update_env_file(config: dict):
    """Update .env file from config"""
    env_lines = []

    # Header
    env_lines.append("# Axeng Configuration")
    env_lines.append("# Generated by: axeng configure")
    env_lines.append("")

    # LLM Provider
    if config.get("llm_provider"):
        provider = config["llm_provider"]
        env_lines.append("# LLM Provider")
        env_lines.append(f"LLM_PROVIDER_ORDER={provider}")

        if provider == "opencode":
            env_lines.append(f"OPENCODE_API_KEY={config.get('opencode_api_key', '')}")
            env_lines.append(f"OPENCODE_MODEL={config.get('opencode_model', 'minimax-m2.5-free')}")
        elif provider == "anthropic":
            env_lines.append(f"ANTHROPIC_API_KEY={config.get('anthropic_api_key', '')}")
        elif provider == "openai":
            env_lines.append(f"OPENAI_API_KEY={config.get('openai_api_key', '')}")
        env_lines.append("")

    # GitHub
    if config.get("github_token"):
        env_lines.append("# GitHub")
        env_lines.append(f"GITHUB_TOKEN={config['github_token']}")
        env_lines.append("")

    # Linear
    if config.get("linear_api_key"):
        env_lines.append("# Linear")
        env_lines.append(f"LINEAR_API_KEY={config['linear_api_key']}")
        env_lines.append("")

    # Telegram (optional)
    if config.get("telegram_bot_token"):
        env_lines.append("# Telegram")
        env_lines.append(f"TELEGRAM_BOT_TOKEN={config['telegram_bot_token']}")
        env_lines.append(f"TELEGRAM_CHAT_ID={config.get('telegram_chat_id', '')}")
        env_lines.append("")

    # Google (optional)
    if config.get("google_enabled"):
        env_lines.append("# Google Workspace")
        env_lines.append("GOOGLE_CLIENT_SECRET=~/.hermes/secrets/google_client_secret.json")
        env_lines.append("GOOGLE_TOKEN_PATH=~/.hermes/secrets/google_token.json")
        env_lines.append("")

    ENV_FILE.write_text("\n".join(env_lines))

@app.command()
def configure():
    """
    Interactive configuration wizard for Axeng
    """
    console.print(Panel.fit(
        "[bold cyan]Axeng Configuration Wizard[/bold cyan]\n"
        "Let's set up your AI chief of staff",
        border_style="cyan"
    ))
    console.print()

    config = load_config()

    # Step 1: LLM Provider
    console.print("[bold]Step 1: Choose your LLM provider[/bold]")
    console.print("Axeng needs an AI model to generate reports and insights.\n")

    llm_choice = Prompt.ask(
        "Which provider would you like to use?",
        choices=["opencode", "anthropic", "openai", "groq"],
        default=config.get("llm_provider", "opencode")
    )
    config["llm_provider"] = llm_choice

    # Get API key for chosen provider
    if llm_choice == "opencode":
        console.print("\n[cyan]OpenCode Zen[/cyan] - Free models available!")
        console.print("Get your API key at: https://opencode.ai/")
        api_key = Prompt.ask(
            "OpenCode API key",
            default=config.get("opencode_api_key", ""),
            password=True
        )
        config["opencode_api_key"] = api_key

        model = Prompt.ask(
            "Model",
            default=config.get("opencode_model", "minimax-m2.5-free"),
            choices=["minimax-m2.5-free", "deepseek-v4-flash-free", "big-pickle"]
        )
        config["opencode_model"] = model

    elif llm_choice == "anthropic":
        console.print("\n[cyan]Anthropic Claude[/cyan] - Best quality")
        console.print("Get your API key at: https://console.anthropic.com/")
        api_key = Prompt.ask(
            "Anthropic API key",
            default=config.get("anthropic_api_key", ""),
            password=True
        )
        config["anthropic_api_key"] = api_key

    elif llm_choice == "openai":
        console.print("\n[cyan]OpenAI[/cyan] - Most compatible")
        console.print("Get your API key at: https://platform.openai.com/")
        api_key = Prompt.ask(
            "OpenAI API key",
            default=config.get("openai_api_key", ""),
            password=True
        )
        config["openai_api_key"] = api_key

    console.print("\n[green]✓[/green] LLM provider configured\n")

    # Step 2: GitHub
    console.print("[bold]Step 2: GitHub integration[/bold]")
    console.print("Connect to GitHub to track repos, PRs, and issues.\n")

    github_token = Prompt.ask(
        "GitHub token (or press Enter to use 'gh' CLI)",
        default=config.get("github_token", ""),
        password=True
    )
    if github_token:
        config["github_token"] = github_token
    else:
        console.print("[dim]Will use GitHub CLI (gh auth login)[/dim]")

    console.print("[green]✓[/green] GitHub configured\n")

    # Step 3: Linear
    console.print("[bold]Step 3: Linear integration[/bold]")
    console.print("Connect to Linear to manage issues and projects.\n")
    console.print("Get your API key at: https://linear.app/settings/api\n")

    linear_key = Prompt.ask(
        "Linear API key",
        default=config.get("linear_api_key", ""),
        password=True
    )
    config["linear_api_key"] = linear_key

    console.print("[green]✓[/green] Linear configured\n")

    # Step 4: Optional services
    console.print("[bold]Step 4: Optional services[/bold]\n")

    # Telegram
    if Confirm.ask("Set up Telegram notifications?", default=config.get("telegram_bot_token") is not None):
        console.print("\nTalk to @BotFather on Telegram to create a bot\n")
        bot_token = Prompt.ask(
            "Telegram bot token",
            default=config.get("telegram_bot_token", ""),
            password=True
        )
        chat_id = Prompt.ask(
            "Telegram chat ID",
            default=config.get("telegram_chat_id", "")
        )
        config["telegram_bot_token"] = bot_token
        config["telegram_chat_id"] = chat_id
        console.print("[green]✓[/green] Telegram configured")

    # Google
    if Confirm.ask("\nSet up Google Calendar integration?", default=config.get("google_enabled", False)):
        console.print("\n[cyan]Google Workspace Setup:[/cyan]")
        console.print("1. Go to https://console.cloud.google.com/")
        console.print("2. Enable Calendar API + Gmail API")
        console.print("3. Create OAuth credentials")
        console.print("4. Download and save to ~/.hermes/secrets/google_client_secret.json")
        console.print("")

        if Confirm.ask("Have you saved the client secret?"):
            config["google_enabled"] = True
            console.print("[green]✓[/green] Google workspace enabled")
            console.print("[dim]Run 'axeng google auth' to complete setup[/dim]")

    console.print()

    # Save configuration
    save_config(config)
    update_env_file(config)

    console.print(Panel.fit(
        "[bold green]✓ Configuration complete![/bold green]\n\n"
        f"Config saved to: {CONFIG_FILE}\n"
        f"Environment: {ENV_FILE}\n\n"
        "[cyan]Next steps:[/cyan]\n"
        "  axeng start    - Start the service\n"
        "  axeng chat     - Chat with Axeng\n"
        "  axeng status   - Check service status",
        border_style="green"
    ))

@app.command()
def chat():
    """
    Interactive chat with Axeng
    """
    console.print(Panel.fit(
        "[bold cyan]Axeng Chat[/bold cyan]\n"
        "Ask me about your team, projects, or engineering metrics",
        border_style="cyan"
    ))
    console.print()

    # Check if configured
    config = load_config()
    if not config.get("llm_provider"):
        console.print("[red]Error:[/red] Axeng not configured")
        console.print("Run: [cyan]axeng configure[/cyan]\n")
        raise typer.Exit(1)

    # Load environment and orchestrator
    try:
        # Load environment variables from AXENG_HOME
        axeng_home = Path(os.getenv("AXENG_HOME", Path.home() / ".axeng"))
        env_file = axeng_home / ".env"

        if env_file.exists():
            # Load .env file
            for line in env_file.read_text().splitlines():
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    os.environ[key.strip()] = value.strip()

        sys.path.insert(0, str(Path(__file__).parent))
        import orchestrator

        # Test connection
        console.print("[dim]Connecting to Axeng intelligence...[/dim]")
        console.print("[green]✓[/green] Connected\n")

    except Exception as e:
        console.print(f"[red]Error loading Axeng:[/red] {e}")
        console.print("Run: [cyan]axeng configure[/cyan] to set up your provider\n")
        raise typer.Exit(1)

    console.print("[dim]Type 'exit' or 'quit' to end the chat[/dim]\n")
    console.print("[dim]I can access your GitHub, Linear, calendar, and team data![/dim]\n")

    # Chat loop with orchestrator
    while True:
        try:
            user_input = Prompt.ask("[bold cyan]You[/bold cyan]")

            if user_input.lower() in ["exit", "quit", "bye"]:
                console.print("\n[cyan]Goodbye! 👋[/cyan]\n")
                break

            # Call orchestrator (it handles tool routing + LLM synthesis)
            console.print(f"\n[bold green]Axeng[/bold green]: ", end="")

            with console.status("[dim]Analyzing and querying your data...[/dim]"):
                try:
                    # Use orchestrator to route query to tools and synthesize response
                    result = orchestrator.orchestrate(
                        goal=user_input,
                        auto_sync=False,  # Don't auto-sync on every query
                        use_llm=True,
                        provider=config.get("llm_provider", "opencode"),
                        max_tokens=1000
                    )

                    # orchestrate returns the synthesized text response
                    console.print(result + "\n")

                except Exception as e:
                    console.print(f"[red]Error: {e}[/red]\n")
                    import traceback
                    console.print(f"[dim]{traceback.format_exc()}[/dim]\n")

        except KeyboardInterrupt:
            console.print("\n\n[cyan]Goodbye! 👋[/cyan]\n")
            break
        except Exception as e:
            console.print(f"\n[red]Error:[/red] {e}\n")
            continue

@app.command()
def start():
    """Start Axeng service"""
    console.print("[cyan]Starting Axeng...[/cyan]")

    # Check if already running
    import socket
    def is_port_in_use(port):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            return s.connect_ex(('localhost', port)) == 0

    if is_port_in_use(3000) and is_port_in_use(3457):
        console.print("[yellow]⚠[/yellow] Axeng appears to be already running")
        console.print("[bold]Next.js UI:[/bold] [link]http://localhost:3000[/link]")
        console.print("[bold]API:[/bold] [link]http://localhost:3457[/link]")
        console.print("\n[dim]Run 'axeng status' to check or 'axeng stop' to stop it[/dim]")
        return

    # Check configuration
    if not CONFIG_FILE.exists():
        console.print("[yellow]Warning:[/yellow] Not configured via CLI")
        console.print("You can run: [cyan]axeng configure[/cyan]")
        console.print("Or edit: [cyan]~/.hermes/.env[/cyan] and [cyan]config/config.yaml[/cyan]\n")

    # Find axeng directory
    axeng_dir = Path(__file__).parent.parent

    # Check if Next.js dependencies are installed
    ui_dir = axeng_dir / "ui" / "nextjs"
    if not (ui_dir / "node_modules").exists():
        console.print("[yellow]Installing dependencies...[/yellow]")
        result = subprocess.run(
            ["npm", "install"],
            cwd=ui_dir,
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            console.print("[red]Error installing dependencies[/red]")
            console.print(result.stderr)
            raise typer.Exit(1)

    # Start using make (don't capture output, let it run in background)
    console.print("[cyan]Starting Axeng Next.js UI...[/cyan]")
    subprocess.Popen(
        ["make", "start"],
        cwd=axeng_dir,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )

    # Wait a moment for services to start
    import time
    time.sleep(3)

    # Check if services started
    if is_port_in_use(3000) or is_port_in_use(3457):
        console.print("[green]✓[/green] Axeng started")
        console.print("\n[bold]Next.js UI:[/bold] [link]http://localhost:3000[/link]")
        console.print("[bold]API:[/bold] [link]http://localhost:3457[/link]")
        console.print("\n[dim]Logs: tail -f /tmp/axeng-*.log[/dim]")
    else:
        console.print("[yellow]⚠[/yellow] Services may take a moment to start")
        console.print("[dim]Check status: axeng status[/dim]")
        console.print("[dim]View logs: axeng logs[/dim]")

@app.command()
def stop():
    """Stop Axeng service"""
    console.print("[cyan]Stopping Axeng...[/cyan]")

    axeng_dir = Path(__file__).parent.parent
    result = subprocess.run(
        ["make", "stop"],
        cwd=axeng_dir,
        capture_output=True,
        text=True
    )

    if result.returncode == 0:
        console.print("[green]✓[/green] Axeng stopped")
    else:
        console.print("[red]Error stopping Axeng[/red]")
        console.print(result.stderr)

@app.command()
def status():
    """Check Axeng service status"""
    import socket
    def is_port_in_use(port):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            return s.connect_ex(('localhost', port)) == 0

    ui_running = is_port_in_use(3000)
    api_running = is_port_in_use(3457)

    if ui_running and api_running:
        console.print("[green]✓[/green] Axeng is [bold green]running[/bold green]")
        console.print("[bold]Next.js UI:[/bold] [link]http://localhost:3000[/link]")
        console.print("[bold]API:[/bold] [link]http://localhost:3457[/link]")
    elif ui_running or api_running:
        console.print("[yellow]⚠[/yellow] Axeng is [bold yellow]partially running[/bold yellow]")
        if ui_running:
            console.print("[green]✓[/green] Next.js UI: [link]http://localhost:3000[/link]")
        if api_running:
            console.print("[green]✓[/green] API: [link]http://localhost:3457[/link]")
        console.print("\n[dim]Try: axeng stop && axeng start[/dim]")
    else:
        console.print("[yellow]○[/yellow] Axeng is [bold]stopped[/bold]")
        console.print("Run: [cyan]axeng start[/cyan]")

@app.command()
def logs():
    """View Axeng logs"""
    axeng_dir = Path(__file__).parent.parent
    subprocess.run(["make", "logs"], cwd=axeng_dir)

@app.command()
def update():
    """Update Axeng to latest version"""
    console.print("[cyan]Updating Axeng...[/cyan]")

    axeng_dir = Path(__file__).parent.parent
    result = subprocess.run(
        ["make", "update"],
        cwd=axeng_dir,
        capture_output=True,
        text=True
    )

    if result.returncode == 0:
        console.print("[green]✓[/green] Updated successfully")
    else:
        console.print("[red]Error updating[/red]")
        console.print(result.stderr)

def main():
    """Main CLI entry point"""
    app()

if __name__ == "__main__":
    main()
